---
kind: Service
apiVersion: v1
metadata:
  name: cornplex-api-service
spec:
  type: ClusterIP
  selector:
    app: cornplex-api-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
# ---
#
# apiVersion: v1
# kind: Service
# metadata:
#   name: {{ include "cornplex-app-api.fullname" . }}
#   labels:
#     {{- include "cornplex-app-api.labels" . | nindent 4 }}
# spec:
#   type: {{ .Values.service.type }}
#   ports:
#     - port: {{ .Values.service.port }}
#       targetPort: http
#       protocol: TCP
#       name: http
#   selector:
#     {{- include "cornplex-app-api.selectorLabels" . | nindent 4 }}
