apiVersion: apps/v1
kind: Deployment
metadata:
  name: cornplex-api-app
  namespace: cornplex-app
  labels:
    app: cornplex-api-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cornplex-api-app
  template:
    metadata:
      labels:
        app: cornplex-api-app
    spec:
      # securityContext: use securityContext for non-root-user, when we get an error related to user permission
      securityContext:
        runAsUser: 1000
        runAsGroup: 3000
        fsGroup: 2000
      containers:
        - name: cornplex-api-image
          image: alpitg/cornplex-api:5000
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: 250m
              memory: 256Mi
          ports:
            - containerPort: 5000
          # env:
          #   - name: ASPNETCORE_URLS
          #     value: http://+:5000
      # # imagePullSecrets: use imagePullSecrets when we use private container
      # imagePullSecrets:
      #   - name: cornplex-api-secret

---
# service - ClusterIP
kind: Service
apiVersion: v1
metadata:
  name: cornplex-api-app
  namespace: cornplex-app
  labels:
    app: cornplex-api-app
spec:
  type: ClusterIP
  selector:
    app: cornplex-api-app
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
---
# service - loadbalancer - for testing
apiVersion: v1
kind: Service
metadata:
  name: cornplex-api-app
  namespace: cornplex-app
spec:
  type: LoadBalancer
  selector:
    app: cornplex-api-app
  ports:
    - port: 5000
      targetPort: 5000
